### PR TITLE
GitHub Action to run build and tests automatically

### PR DESCRIPTION
**Pull request by jgstew**
First, the bad news. For some reason the command line driven Swift build doesn't succeed currently. Not sure exactly why it is different than doing the build and test through xcode that doesn't seem to complain. Seems like the command line build is more strict?

If it wasn't for that, then this GitHub action would allow for automated testing of this project across multiple swift versions on MacOS and if desired, Ubuntu as well. This also helps provide feedback and assurances when anyone creates a pull request with code to contribute that the code has been built and tested.

I tried a few things to address the build failures, but I couldn't resolve them all so I ended up reverting those changes back so that this only includes the GitHub Action itself.

Example build failure output is here: https://github.com/jgstew/Blackbird/actions/runs/3690064221/jobs/6246696395

Sadly this probably isn't useful unless the build failures are resolved, which is outside of my knowledge, which is much more so with GitHub Actions than it is with Swift development.

### CODE REVIEW

**Comment by marcoarment** [comment]
Thanks for doing all of this! For whatever reason, doing the same thing on my Mac (command-line `swift build`) works fine. I'm going to see if I can get it working.

**Comment by jgstew** [comment]
I had been meaning to try `swift build` command on my Intel Mac, but the only thing I tried was in Xcode. I don't know why the GitHub Action version of swift would be more strict than running it in xcode unless there is some different defaults or something.

**Comment by starsolutions** [comment]
@jgstew - I was just going to take a stab at debugging why the build was failing in the action.  Making a branch and rerunning the action, the build and tests are passing for me.  Maybe something was fixed with the GitHub runner image?

**Comment by marcoarment** [comment]
Great, thanks!

**Comment by jgstew** [comment]
Yep, just validated, this is working! https://github.com/jgstew/Blackbird/actions/runs/4188618316/jobs/7259972526

**Comment by jgstew** [comment]
Now that this is merged and working, all future Pull Requests and commits to main should result in automated build and tests on an Intel Mac github action runner, which in addition to providing feedback in the PR itself, should show up here: https://github.com/marcoarment/Blackbird/actions

**Pull request merged**
